
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 05 15:33:58 CEST 2011
//----------------------------------------------------

package planningMaster.analyseurs;


/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed Oct 05 15:33:58 CEST 2011
  */
public class ParserPlanning extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ParserPlanning() {super();}

  /** Constructor which sets the default scanner. */
  public ParserPlanning(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserPlanning(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\010\000\002\003\004\000\002\002\004\000\002\006" +
    "\004\000\002\004\004\000\002\005\011\000\002\007\003" +
    "\000\002\010\003\000\002\002\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\005\000\004\006\004\001\002\000\004\015\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\000\001\002" +
    "\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\005\000\004\003\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserPlanning$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserPlanning$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserPlanning$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ParserPlanning$actions {
  private final ParserPlanning parser;

  /** Constructor */
  CUP$ParserPlanning$actions(ParserPlanning parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ParserPlanning$do_action(
    int                        CUP$ParserPlanning$act_num,
    java_cup.runtime.lr_parser CUP$ParserPlanning$parser,
    java.util.Stack            CUP$ParserPlanning$stack,
    int                        CUP$ParserPlanning$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserPlanning$result;

      /* select the action based on the action number */
      switch (CUP$ParserPlanning$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // texte ::= 
            {
              Object RESULT =null;

              CUP$ParserPlanning$result = parser.getSymbolFactory().newSymbol("texte",0, ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.peek()), RESULT);
            }
          return CUP$ParserPlanning$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // grandePause ::= GRANDEPAUSE 
            {
              Object RESULT =null;

              CUP$ParserPlanning$result = parser.getSymbolFactory().newSymbol("grandePause",6, ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.peek()), RESULT);
            }
          return CUP$ParserPlanning$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // petitePause ::= PETITEPAUSE 
            {
              Object RESULT =null;

              CUP$ParserPlanning$result = parser.getSymbolFactory().newSymbol("petitePause",5, ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.peek()), RESULT);
            }
          return CUP$ParserPlanning$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // entry ::= SLOT SEPARATOR NAME SEPARATOR NAME SEPARATOR OPTIONS 
            {
              Object RESULT =null;

              CUP$ParserPlanning$result = parser.getSymbolFactory().newSymbol("entry",3, ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.elementAt(CUP$ParserPlanning$top-6)), ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.peek()), RESULT);
            }
          return CUP$ParserPlanning$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // date ::= DATECST DATE 
            {
              Object RESULT =null;

              CUP$ParserPlanning$result = parser.getSymbolFactory().newSymbol("date",2, ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.elementAt(CUP$ParserPlanning$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.peek()), RESULT);
            }
          return CUP$ParserPlanning$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // master ::= MASTERCST MASTER 
            {
              Object RESULT =null;

              CUP$ParserPlanning$result = parser.getSymbolFactory().newSymbol("master",4, ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.elementAt(CUP$ParserPlanning$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.peek()), RESULT);
            }
          return CUP$ParserPlanning$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= salle EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.elementAt(CUP$ParserPlanning$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.elementAt(CUP$ParserPlanning$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserPlanning$stack.elementAt(CUP$ParserPlanning$top-1)).value;
		RESULT = start_val;
              CUP$ParserPlanning$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.elementAt(CUP$ParserPlanning$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserPlanning$parser.done_parsing();
          return CUP$ParserPlanning$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // salle ::= ROOMCST ROOM 
            {
              Object RESULT =null;

              CUP$ParserPlanning$result = parser.getSymbolFactory().newSymbol("salle",1, ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.elementAt(CUP$ParserPlanning$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPlanning$stack.peek()), RESULT);
            }
          return CUP$ParserPlanning$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

