
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 05 15:33:58 CEST 2011
//----------------------------------------------------

package planningMaster.analyseurs;

/** CUP generated class containing symbol constants. */
public class TypeSymboles {
  /* terminals */
  public static final int SEPARATOR = 14;
  public static final int MASTER = 12;
  public static final int MASTERCST = 3;
  public static final int DATE = 8;
  public static final int OPTIONS = 13;
  public static final int ENTREPRISE = 10;
  public static final int EOF = 0;
  public static final int DATECST = 2;
  public static final int ROOMCST = 4;
  public static final int error = 1;
  public static final int SLOT = 7;
  public static final int GRANDEPAUSE = 6;
  public static final int PETITEPAUSE = 5;
  public static final int ROOM = 11;
  public static final int NAME = 9;
}

