
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 05 14:41:33 CEST 2011
//----------------------------------------------------

package init.analyseurs;

/** CUP generated class containing symbol constants. */
public class TypeSymboles {
  /* terminals */
  public static final int READ = 4;
  public static final int IDENT = 5;
  public static final int INTEGER = 6;
  public static final int SEPVAR = 9;
  public static final int PROG = 2;
  public static final int EOF = 0;
  public static final int DECLINT = 3;
  public static final int FININSTR = 8;
  public static final int error = 1;
  public static final int AFF = 7;
}

